#!/usr/bin/env python3
"""Generate conservative browser risk floors from the canonical Python rules."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "site" / "playground" / "risk-floors.js"

# Run against this checkout even when another readtheplan version is installed.
sys.path.insert(0, str(ROOT / "src"))

from readtheplan.plan import analyze_plan_file  # noqa: E402
from readtheplan.rules import _shared  # noqa: E402

ACTION_TUPLES = (
    ("create",),
    ("update",),
    ("delete",),
    ("delete", "create"),
    ("create", "delete"),
    ("forget",),
)


def _risk(resource_type: str, actions: tuple[str, ...]) -> str:
    """Classify one exact Terraform action tuple through the public analyzer."""
    result = analyze_plan_file(
        {
            "format_version": "1.2",
            "resource_changes": [
                {
                    "address": f"{resource_type}.risk_floor",
                    "type": resource_type,
                    "name": "risk_floor",
                    "change": {
                        "actions": list(actions),
                        "before": {},
                        "after": {},
                    },
                }
            ],
        }
    ).resource_changes[0]
    return result.risk


def main() -> None:
    resource_types = sorted(str(key) for key in _shared._RULE_REGISTRY)
    payload = {
        "schemaVersion": 2,
        "resourceTypeCount": len(resource_types),
        # Keep ordered tuples distinct: Terraform uses replacement order to
        # communicate create-before-destroy versus destroy-before-create.
        "actionTuples": [list(actions) for actions in ACTION_TUPLES],
        "floors": {
            resource_type: [_risk(resource_type, actions) for actions in ACTION_TUPLES]
            for resource_type in resource_types
        },
    }
    serialized = json.dumps(payload, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
    source = "\n".join(
        [
            "// Generated by site/scripts/build-classifier-risk-floors.py; do not edit.",
            "(function (root) {",
            f"  const data = {serialized};",
            '  if (typeof module !== "undefined" && module.exports) module.exports = data;',
            "  else root.READTHEPLAN_RISK_FLOORS = data;",
            '})(typeof globalThis !== "undefined" ? globalThis : this);',
            "",
        ]
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8", newline="\n") as output_file:
        output_file.write(source)
    print(f"Generated {len(resource_types)} classifier risk floors -> {OUTPUT}")


if __name__ == "__main__":
    main()
