from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"


def _legacy_site_has_client_onboarding_surface() -> None:
    html = (SITE / "index.html").read_text(encoding="utf-8")
    app = (SITE / "app.js").read_text(encoding="utf-8")

    assert "readtheplan" in html
    assert "No plan upload" in html
    assert "SOC 2" in html
    assert "ISO 27001" in html
    assert "HIPAA" in html
    assert 'id="top"' in html
    assert 'id="setup"' in html
    assert 'id="agent"' in html
    assert 'id="pilot"' in html
    assert 'id="gen-output"' in html
    assert 'id="gen-thresh"' in html
    assert 'id="install-cmd"' in html
    assert 'id="copy-install"' in html
    assert 'id="p-org"' in html
    assert 'id="p-email"' in html
    assert 'id="p-blocker"' in html
    assert "fail-on-threshold" in html
    assert 'class="terminal"' in html
    assert "readtheplan analyze --framework" in html
    assert "Terraform + OpenTofu" in html
    assert "pip install readtheplan" in html
    assert "/tools/terraform-risk-calculator/" in html
    assert "/tools/soc2-cloud-control-mapper/" in html
    assert "/mcp/" in html
    assert 'rel="canonical"' in html
    assert "og:image" in html
    assert "v0.3.0" in html
    assert "SOC 2" in html
    assert "ISO 27001" in html
    assert "HIPAA" in html
    assert "Upload a plan" not in html
    assert "gmail.com" not in html
    assert "terraform show -json tfplan > " in app
    assert "--framework" in app
    assert "--evidence" in app
    assert "readtheplan-evidence.json" in app
    assert "--sign" in app
    assert "id-token: write" in app
    assert "actions/upload-artifact@v4" in app
    assert "No raw Terraform plan is attached." in app
    assert "No raw plan submission is needed" in app
    assert "gateScript" in app
    assert "readtheplan-summary.json" in app
    assert "loadDemoData" in app
    assert "/demo-evidence.json" in app
    assert "workflow_run:" in app
    assert "actions: read" in app
    assert "actions/download-artifact@v4" in app
    assert "Do not expose cloud credentials to forked pull_request jobs." in app
    assert "terraform init -input=false" not in app
    assert "PILOT_HANDOFF_EMAIL" in app
    assert "info@readtheplan.dev" in app
    assert "repoProfileLabels" in app
    assert "maturityLabels" in app
    assert "AWS resource priorities" in app
    assert "Client context stayed in the browser until this email was generated by the user." in app
    assert "replace PILOT_HANDOFF_EMAIL in site/app.js before production use." in app
    assert "gmail.com" not in app


def test_site_has_client_onboarding_surface() -> None:
    html = (SITE / "index.html").read_text(encoding="utf-8")

    assert "readtheplan" in html
    assert "No plan upload" in html
    assert "SOC 2" in html
    assert "ISO 27001" in html
    assert "HIPAA" in html
    assert 'id="top"' in html
    assert 'id="matrix-rain"' in html
    assert 'id="webgl-canvas"' in html
    assert 'id="how-it-works"' in html
    assert 'id="setup"' in html
    assert 'id="agent"' in html
    assert 'id="community"' in html
    assert 'id="resources"' in html
    assert 'id="compare"' in html
    assert 'id="gen-output"' in html
    assert "Turn Terraform JSON plans into stable risk tiers" in html
    assert "/tools/terraform-risk-calculator/" in html
    assert "/tools/soc2-cloud-control-mapper/" in html
    assert "/mcp/" in html
    assert "/brief/" in html
    assert "/playground/" in html
    assert 'rel="canonical"' in html
    assert "og:image" in html
    assert "Upload a plan" not in html
    assert "gmail.com" not in html


def test_site_build_contract_for_cloudflare_pages() -> None:
    package = (SITE / "package.json").read_text(encoding="utf-8")
    build_script = (SITE / "scripts" / "build.js").read_text(encoding="utf-8")
    workflow = (ROOT / ".github" / "workflows" / "site.yml").read_text(encoding="utf-8")

    assert '"build": "node scripts/build.js"' in package
    assert "site/dist" in (ROOT / ".gitignore").read_text(encoding="utf-8")
    assert "X-Content-Type-Options: nosniff" in build_script
    assert "Content-Security-Policy" in build_script
    assert "https://static.cloudflareinsights.com" in build_script
    assert "https://plausible.io" not in build_script
    assert "font-src 'self'" in build_script
    assert "img-src 'self' data:" in build_script
    assert "Strict-Transport-Security" in build_script
    assert "Access-Control-Allow-Origin: https://readtheplan.dev" in build_script
    assert "examples" in build_script
    assert "02-dangerous-replacement" in build_script
    assert "demo-evidence.json" in build_script
    assert "browsing-topics=()" in build_script
    assert "Cross-Origin-Opener-Policy" in build_script
    assert "assetDirs" in build_script
    assert '"fonts"' in build_script
    assert '"img"' in build_script
    assert '"tools"' in build_script
    assert '"resources"' in build_script
    assert '"mcp"' in build_script
    assert '"brief"' in build_script
    assert "npm --prefix site run build" in workflow

    homepage = (SITE / "index.html").read_text(encoding="utf-8")
    assert "https://plausible.io" not in homepage

    for asset in [
        "404.html",
        "_redirects",
        "favicon.svg",
        "og-image.png",
        "robots.txt",
        "sitemap.xml",
    ]:
        assert (SITE / asset).exists()
        assert asset in build_script


def test_static_seo_tools_preserve_local_first_privacy() -> None:
    routes = [
        "tools/terraform-risk-calculator/index.html",
        "tools/soc2-cloud-control-mapper/index.html",
        "resources/terraform-s3-bucket-risk/index.html",
        "resources/terraform-iam-policy-risk/index.html",
        "resources/terraform-security-group-0-0-0-0-risk/index.html",
        "resources/terraform-cloudwatch-log-retention-risk/index.html",
    ]
    pages = [(SITE / route).read_text(encoding="utf-8") for route in routes]
    combined = "\n".join(pages)
    sitemap = (SITE / "sitemap.xml").read_text(encoding="utf-8")
    tools_js = (SITE / "tools" / "tools.js").read_text(encoding="utf-8")

    for route in routes:
        assert (SITE / route).exists()
        url_path = "/" + route.removesuffix("index.html")
        assert url_path in sitemap

    assert "Terraform Risk Calculator" in combined
    assert "SOC 2 Cloud Control Mapper" in combined
    assert "raw Terraform plans stay local" in combined
    assert 'id="riskCalculator"' in combined
    assert 'type="number"' in combined
    assert "Calculate risk" in combined
    assert "SOC 2 control family map" in combined
    assert "Terraform S3 Bucket Risk" in combined
    assert "Terraform IAM Policy Risk" in combined
    assert "Terraform Security Group 0.0.0.0/0 Risk" in combined
    assert "Terraform CloudWatch Log Retention Risk" in combined
    assert "Request pilot setup" in combined
    assert "info@readtheplan.dev" in combined
    assert 'itemscope itemtype="https://schema.org/FAQPage"' in combined
    assert "new FormData(calculator)" in tools_js

    assert "Upload a plan" not in combined
    assert 'type="file"' not in combined
    assert "<form" in combined
    assert "action=" not in combined
    for prohibited in [
        "hosted analyzer",
        "hosted plan analysis",
        "API endpoint",
        "store uploaded",
        "stored plan",
    ]:
        assert prohibited.lower() not in combined.lower()


def test_mcp_landing_page_productizes_local_preview_only() -> None:
    mcp = (SITE / "mcp" / "index.html").read_text(encoding="utf-8")
    sitemap = (SITE / "sitemap.xml").read_text(encoding="utf-8")

    assert (SITE / "mcp" / "index.html").exists()
    assert "/mcp/" in sitemap

    for expected in [
        "Local MCP Terraform reviewer",
        "Give your AI coding agent a Terraform/SOC 2 reviewer that runs locally",
        "Local-first",
        "No raw plan upload",
        "No hosted MCP service",
        "No hosted plan analysis",
        'pip install "readtheplan[mcp]"',
        "readtheplan mcp",
        "analyze_plan",
        "agent_gate",
        "proceed/warn/block",
        "PR reviewer",
        "SOC 2 evidence prep",
        "Dangerous change triage",
        "Auditor-friendly summary",
        "CloudFormation",
        "Kubernetes",
        "Terraform-first today",
        "Request pilot setup",
        "info@readtheplan.dev",
        "auth design",
        "least privilege",
        "audit logs",
        "Custom engagement",
    ]:
        assert expected in mcp

    for prohibited in [
        "Upload a plan",
        "hosted MCP endpoint",
        "hosted MCP platform",
        "hosted plan analyzer",
        "API endpoint",
        "submit your plan",
        "store uploaded",
        "stored plan",
    ]:
        assert prohibited.lower() not in mcp.lower()

    assert 'type="file"' not in mcp
    assert "<form" not in mcp


def test_weekly_brief_free_community_slice() -> None:
    brief_path = SITE / "brief" / "index.html"
    sample_path = SITE / "brief" / "sample-001" / "index.html"
    sitemap = (SITE / "sitemap.xml").read_text(encoding="utf-8")
    homepage = (SITE / "index.html").read_text(encoding="utf-8")
    assert brief_path.exists()
    assert sample_path.exists()
    assert "/brief/" in sitemap
    assert "/brief/sample-001/" in sitemap
    assert "/brief/" in homepage

    combined = brief_path.read_text(encoding="utf-8") + "\n" + sample_path.read_text(encoding="utf-8")  # noqa: E501

    for expected in [
        "Weekly Terraform/SOC 2 change intelligence for platform teams",
        "free community brief",
        "monitor, filter, analyze, package, publish",
        "platform/SRE teams",
        "DevOps consultancies",
        "SOC 2 consultants",
        "seed-stage infra/devtool startups",
        "Top 5 infra/compliance changes",
        "Why they matter",
        "Terraform/SOC2 risk angle",
        "Action checklist",
        "readtheplan CTA",
        "Public sample",
        "Open weekly brief",
        "Community suggestions",
        "Reusable integrations",
        "Suggest the next issue",
        "Terraform/OpenTofu",
        "AWS logging",
        "AWS IAM",
        "Security group ingress",
        "GitHub Actions permission expansion",
        "SOC 2 evidence",
        "readtheplan progress",
        "Demo issue",
    ]:
        assert expected in combined

    for prohibited in [
        'type="file"',
        "Upload a plan",
        "submit your plan",
        "Start hosted analyzer",
        "hosted plan analyzer is available",
        "Create account",
        "Sign up",
        "Stripe",
        "Checkout",
        "Subscribe now",
        "paid output",
        "$499",
        "Managed (Paid)",
        "Enterprise (Custom)",
        "storage bucket",
        "store uploaded",
        "stored plan",
        "cron job is enabled",
        "scheduled delivery is enabled",
        "automatic scheduled delivery is enabled",
    ]:
        assert prohibited.lower() not in combined.lower()

    assert "<form" not in combined


def test_pricing_is_free_forever_and_has_no_paid_tiers() -> None:
    pricing = (SITE / "pricing" / "index.html").read_text(encoding="utf-8")

    for expected in [
        "Free forever. No tiers.",
        "$0",
        "No feature or usage paywall",
        "No behavioral advertising",
        "Optional commercial-agent monetization",
    ]:
        assert expected in pricing

    for prohibited in ["$499", "Managed", "Enterprise", "free trial", "Contact for pricing"]:
        assert prohibited.lower() not in pricing.lower()


def test_docs_routes_are_sitemap_listed_and_landing_aligned() -> None:
    sitemap = (SITE / "sitemap.xml").read_text(encoding="utf-8")
    css = (SITE / "styles.css").read_text(encoding="utf-8")
    docs_routes = [
        "docs/index.html",
        "docs/quickstart/index.html",
        "docs/cli/index.html",
        "docs/github-action/index.html",
    ]

    for route in docs_routes:
        path = SITE / route
        html = path.read_text(encoding="utf-8")
        url_path = "/" + route.removesuffix("index.html")

        assert path.exists()
        assert url_path in sitemap
        assert '<link rel="stylesheet" href="/matrix.css" />' in html
        assert '<header class="topbar g"' in html
        assert 'class="version-cell gc">v0.3.0' in html
        assert "readtheplan" in html

    assert "/demo/" in sitemap
    assert "/playground/" in sitemap
    assert "Landing-aligned shared page theme" in css
    assert "Final landing-aligned cascade guard" in css


def test_site_redesign_visual_contract() -> None:
    css = (SITE / "styles.css").read_text(encoding="utf-8")
    docs = (SITE / "docs" / "index.html").read_text(encoding="utf-8")

    assert '"Departure Mono"' in css
    assert '"JetBrains Mono"' in css
    assert 'url("./fonts/DepartureMono-Regular.woff2")' in css
    assert 'url("./fonts/JetBrainsMono-Regular.woff2")' in css
    assert "--background: #041C1C;" in css
    assert "--accent: #FFBD38;" in css
    assert 'background-image: url("./img/noise.svg")' in css
    assert ".g {" in css
    assert ".gc {" in css
    assert "Landing-aligned shared page theme" in css
    assert "--background: #0a0a0a;" in css
    assert "--foreground: #f0f0f0;" in css
    assert ".topbar.g {" in css
    assert ".hero-spacer {" in css
    assert "Final landing-aligned cascade guard" in css
    assert "@media (max-width: 720px)" in css
    assert '<link rel="stylesheet" href="/matrix.css" />' in docs
    assert '<header class="topbar g"' in docs
    assert 'class="version-cell gc">v0.3.0' in docs

    for asset in [
        "fonts/DepartureMono-Regular.woff2",
        "fonts/JetBrainsMono-Regular.woff2",
        "fonts/LICENSE-DepartureMono.txt",
        "fonts/LICENSE-JetBrainsMono.txt",
        "img/noise.svg",
    ]:
        assert (SITE / asset).exists()
