"""Guard: committed example outputs must match current CLI output.

The files under examples/*/analysis.md and analysis.json are generated by
scripts/regenerate-examples.sh. They are documentation users compare their own
output against, so they must never drift from the engine. If this test fails,
run `scripts/regenerate-examples.sh` and commit the result.
"""
from __future__ import annotations

import contextlib
import io
import os
from pathlib import Path

import pytest

from readtheplan.cli import main

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
EXAMPLE_DIRS = sorted(
    d.name for d in EXAMPLES.iterdir() if (d / "plan.json").exists()
)


def _run(argv: list[str]) -> str:
    # Run from the repo root so the plan path embedded in output matches the
    # committed files (regenerate-examples.sh uses repo-relative paths).
    cwd = os.getcwd()
    os.chdir(ROOT)
    try:
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            rc = main(argv)
    finally:
        os.chdir(cwd)
    assert rc == 0, f"CLI exited {rc} for {argv}"
    return _normalize_plan_path(buf.getvalue())


def _normalize_plan_path(output: str) -> str:
    lines = []
    for line in output.splitlines():
        if line.startswith("# readtheplan summary: "):
            line = line.replace("\\", "/")
        elif line.startswith('  "path": '):
            line = line.replace("\\\\", "/")
        lines.append(line)
    return "\n".join(lines) + ("\n" if output.endswith("\n") else "")


@pytest.mark.parametrize("name", EXAMPLE_DIRS)
def test_example_markdown_is_fresh(name: str) -> None:
    plan = f"examples/{name}/plan.json"
    committed = EXAMPLES / name / "analysis.md"
    if not committed.exists():
        pytest.skip(f"{name} has no analysis.md")
    produced = _run(["analyze", plan])
    assert produced.splitlines() == committed.read_text().splitlines(), (
        f"{name}/analysis.md is stale — run scripts/regenerate-examples.sh"
    )


@pytest.mark.parametrize("name", EXAMPLE_DIRS)
def test_example_json_is_fresh(name: str) -> None:
    plan = f"examples/{name}/plan.json"
    committed = EXAMPLES / name / "analysis.json"
    if not committed.exists():
        pytest.skip(f"{name} has no analysis.json")
    produced = _run(["analyze", "--format", "json", "--framework", "soc2", plan])
    assert produced.splitlines() == committed.read_text().splitlines(), (
        f"{name}/analysis.json is stale — run scripts/regenerate-examples.sh"
    )
