apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: readtheplan
    newName: nexus.devsecops.internal/docker-hosted/readtheplan
    digest: sha256:e3af427b90d73f7116ab125dfb1c60a7a15ebc588a924910d96a7d0d766afd25
patches:
  - target:
      kind: Job
      name: readtheplan-smoke
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: nexus-registry
